#ifndef RECAP_LABELLER_GUI_ICONS_H_INCLUDE
#define RECAP_LABELLER_GUI_ICONS_H_INCLUDE

#include <IconsFontAwesome6.h>

#define FILE_ERR_ICON ICON_FA_FILE_CIRCLE_EXCLAMATION
#define ERR_ICON ICON_FA_TRIANGLE_EXCLAMATION
#define DEBUG_INFO_ICON ICON_FA_GEAR
#define ANNOTATED_TASK_ICON ICON_FA_SQUARE_CHECK
#define SUGGESTED_ANNOTATION_TASK_ICON ICON_FA_STAR_OF_LIFE
#define HINT_ICON ICON_FA_LIGHTBULB
#define DELETE_ICON ICON_FA_TRASH_CAN
#define EXIT_ICON ICON_FA_XMARK
#define SHUFFLE_ICON ICON_FA_SHUFFLE
#define UNSHUFFLE_ICON ICON_FA_SORT
#define SKIP_TASK_ICON ICON_FA_FORWARD
#define FILTER_ICON ICON_FA_FILTER
#define FILTER_CANCEL_ICON ICON_FA_FILTER_CIRCLE_XMARK
#define SCROLL_TO_TOP_ICON ICON_FA_ARROWS_UP_TO_LINE
#define SCROLL_TO_BOTTOM_ICON ICON_FA_ARROWS_DOWN_TO_LINE
#define SCROLL_TO_TASK_ICON ICON_FA_ARROWS_TO_DOT
#define ICON_TEXT_SPACE "  "

#endif // RECAP_LABELLER_GUI_ICONS_H_INCLUDE
