repos:
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: scripts/run-clang-format.py
        args: ["--in-place"]
        language: system
        types_or: [c, c++]
  - repo: https://github.com/cmake-lint/cmake-lint
    rev: "1.4.3"
    hooks:
      - id: cmakelint
