name: Build
on:
  push:
    branches: [main]
jobs:
  build-windows:
    env:
      BUILD_TYPE: Release
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure
        run: |
          cmake \
            -B build \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DEXPORT_CHECK_TARGETS=off \
            -G "Visual Studio 17 2022"
      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel
      - name: Run tests
        env:
          GTEST_COLOR: "yes"
        run: ctest --test-dir build --build-config ${{ env.BUILD_TYPE }} --output-on-failure
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: recapctl-windows
          path: build/implot-rects*.exe
