name: Build
on:
  push:
    branches: [main]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

  build-windows:
    needs: [lint]
    env:
      BUILD_TYPE: Release
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      # Need to configure before Python otherwise it will override the PATH set by the virtualenv
      - name: Configure MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create requirements.txt
        run: echo "numpy==1.26.0" > requirements.txt
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.10'
      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Bootstrap vcpkg
        run: vcpkg/bootstrap-vcpkg.bat
      - name: Configure
        run: cmake --preset windows -DBUILD_DEMO=off
      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

      - name: Run tests
        env:
          GTEST_COLOR: "yes"
        run: ctest --test-dir build --build-config ${{ env.BUILD_TYPE }} --output-on-failure

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: recap-labeller
          path: build/${{ env.BUILD_TYPE }}/recap-labeller*.exe
